[project]
name = "roboquant-interactive"
version = "0.2.0"
description = "Examples hwo to usue roboquant with Jupyter and other interactive tools"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "marimo>=0.11.26",
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "roboquant>=1.6.1",
    "streamlit>=1.43.2",
]
